### ISSUE TITLE
Verify that SO works for Downside

### ISSUE THREAD

**Issue by brittcyr** [Dual-Finance/staking-options#5]
Run an e2e test, logging the results here

**Comment by brittcyr** [comment]
Quick inspection of the code makes it seem like it might just work
https://github.com/Dual-Finance/staking-options/blob/master/programs/staking-options/src/instructions/config.rs#L89

Code is already setup to handle variable base and quote

**Comment by brittcyr** [comment]
Unit tests are still passing

**Comment by brittcyr** [comment]
Did a little refactoring that should make it more clear that it is token agnostic. Still considering reformating the strike to a float with it though

**Comment by brittcyr** [comment]
Looking through how other projects handle this, mango uses U80I48 a lot, but zeta and serum just normalize to lot size. I will do that, but that will require that the project sets a lot size from the start which shouldnt be a problem

**Comment by brittcyr** [comment]
Likely to have that running tonight

**Comment by brittcyr** [comment]
Got tests passing for updates to make the decimals handling similar to zeta/serum

**Comment by DonDuala** [comment]
Close this?
