### ISSUE TITLE
Do not charge fee on stablecoin pairs

### ISSUE THREAD

**Issue by brittcyr** [Dual-Finance/staking-options#56]
Staking options have a use case of fixing a price for a swap so a DAO can slowly vote and not be subject to price movement. This use case does not merit taking a fee to DUAL DAO though.

**Comment by brittcyr** [comment]
Or at least a reduced fee.
@DonDuala what pairs should be exempt?

**Comment by DonDuala** [comment]
mints to start if any of these are combined together base & quote
USDC: EPjFWdd5AufqSSqeM2qN1xzybapC8G4wEGGkZwyTDt1v
USDT: Es9vMFrzaCERmJfrF4H2FYD4KCoNkY11McCe8BenwNYB
DAIpo: EjmyN6qEC1Tf1JxiG1ae7UTJhUxSwk1TCWNWqxWV4J6o
USDH: USDH1SM1ojwWUga67PGrgFWUHibbjqMvuMaDkRJTgkX
sDAIpo: TBD

Ideally set fees for these to 1bp

also could include SOL vs LSTs as reduced fee category ~5bp fees

could try to line up with openbook fees https://github.com/openbook-dex/program/pull/5/files but looks like its not a very full list

**Comment by DonDuala** [comment]
Will want to extend this possibly for any similar base/quote pair such as wBTCpo/tBTC/wBTCnative or rETHpo/wstETHpo
